### ISSUE TITLE
run scanner - mac os x

### ISSUE THREAD

**Issue by baptistapedro** [mwrlabs/drozer#206] opened 2016-05-06 02:18 UTC
drozer Console (v2.3.4)

dz> run scanner.provider.finduris -a com.myapp

Scanning com.tinder...

drozer could not find or compile a required extension library.

I have been running through this warning while using the scanner I am not sure what is going on,

el capitan osx.

**Comment by javixeneize** [comment] 2016-05-13 15:11
Hi

Even with sieve apk it doesnt work... 

run scanner.provider.finduris -a com.mwr.example.sieve 

Is it a bug in drozer, or is the apk itself?

Thanks

**Comment by HenryHoggard** [comment] 2016-05-17 10:05
Duplicate of the following solved issues.
https://github.com/mwrlabs/drozer/issues/111
https://github.com/mwrlabs/drozer/issues/147
https://github.com/mwrlabs/drozer/issues/179

**Comment by MrMugiwara** [comment] 2016-11-26 12:59
the problem still always persist on MacOS Sierra 11.12.1 :

dz> run tools.setup.busybox 
drozer could not find or compile a required extension library.

dz> run scanner.provider.finduris 
Scanning com.mobeam.barcodeService...
drozer could not find or compile a required extension library.

dz>

**Comment by HenryHoggard** [comment] 2016-12-08 09:48
What version of Drozer are you using and how did you install it?

**Comment by amarekano** [comment] 2017-06-27 17:18
Hi @MrMugiwara, I've just installed drozer 2.4.2 on Sierra 10.12.5 (this being the latest OSX release) and I've not been able to reproduce the bug.

I would recommend installing the latest drozer release and attempt to reproduce the issue.
The latest release can be downloaded from https://github.com/mwrlabs/drozer/releases/tag/2.4.2

If you're still unable to get drozer working, please open a new issue and fill in the issue template.

**Closed by amarekano** 2017-06-27 17:18 UTC
Labels: Awaiting Feedback, Support
