### ISSUE TITLE
javac path not found

### ISSUE THREAD

**Issue by arunsunkumar** [mwrlabs/drozer#187] opened 2016-01-27 04:41 UTC
Hi

I am getting below error while executing below commands:

dz> run app.package.manifest org.owasp.goatdroid.fourgoats
Could not find javac. Please ensure that it is installed and on your PATH.

If this error persists, specify the path in the ~/.drozer_config file:

    [executables]
    javac = C:\path\to\javac
Could not find javac on your PATH.

I  have given the javac path in .drozer.config file , but still issue persist

i have installed jdk version 1.6.0_45.

**Comment by HenryHoggard** [comment] 2016-02-02 13:32
What is the contents of your .drozer_config?
The path shouldn't be `javac = C:\path\to\javac` as this is an example path.

**Comment by HenryHoggard** [comment] 2016-02-02 13:34
Closed, duplicate of https://github.com/mwrlabs/drozer/issues/186

**Closed by HenryHoggard** 2016-02-02 13:34 UTC
